[project]
name = "scientific-computing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Henry Zwart", email = "henrybzwart@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numba>=0.61.0",
    "numpy>=2.1.3",
    "scipy>=1.15.1",
]

[project.scripts]
#code = "code:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
