name: Tests

on:
  push: # Whenever new code enters the main branch
    branches:
      - main
  pull_request: # Whenever we create a pull-request into main
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.29"

      - name: Run tests
        run: uv run pytest

